### ISSUE TITLE
Create prometheus metrics endpoint to report latency and gas usage

### ISSUE THREAD

**Issue by dshiell** [polymerdao/ibc-explorer#2]
Description
------------
Create prometheus metrics endpoint on the backend API to report latency and gas usage over the last hour (TBD). This endpoint can return metrics which are external to the Polymer chain.

Reasoning
----------
We want to be able to track these external metrics in addition to on-chain IBC metrics for KPI and usage tracking.

Acceptance Criteria
--------------------
- Ensure that the /metrics endpoint returns latency and gas usage metrics matching the existing ibc-explorer metrics page and is consumable by Prometheus and available in grafana/gcp monitoring

**Comment by dshiell** [comment]
@dshiell PR to review

**Comment by dshiell** [comment]
Deployed verified contracts, need to finish investigation. Currently not working as expected.

**Comment by Inkvi** [comment]
Can be accessed at https://explorer.stg.testnet.polymer.zone/metrics and https://explorer.prod.testnet.polymer.zone/metrics
