### ISSUE TITLE
Search channels page by full address, including '0x'

### ISSUE THREAD

**Issue by tmsdkeys** [polymerdao/ibc-explorer#21]
Description
------------
-  Make it so that when querying in the channels page by address, that you can input '0xabcdef...' values including hex prefix. Now developers have to manually copy without 0x

Reasoning
----------
- Small change which drastically improves UX. All explorers allow to copy 0x addresses

Acceptance Criteria
--------------------
1.  Ensure the search filter supports both addresses with or without the '0x' prefix

**Comment by mvpoyatt** [comment]
Fixed in new explorer
