### ISSUE TITLE
Add last refreshed time on explorer to indicate packet cache is updating.

### ISSUE THREAD

**Issue by dshiell** [polymerdao/ibc-explorer#73]
Context: It is difficult to distinguish between the ibc-explorer taking longer to update and low packet activity. We could at a `last refreshed` field at the bottom of the page so that it's obvious when there are real delays in updating the packet cache.

**Comment by Inkvi** [comment]
Won't be relevant when the indexer has packets table populated

**Comment by molla202** [comment]
Exactly
